/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rpp_RPP */

#ifndef _Included_com_example_rpp_RPP
#define _Included_com_example_rpp_RPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rpp_RPP
 * Method:    xxx
 * Signature: ([D[D[D[DI[[DZDDILcom/example/rpp/RPP/PoseResult;)V
 */
JNIEXPORT void JNICALL Java_com_camera_pose_estimate_rpp_RPP_estimate
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobjectArray, jboolean, jdouble, jdouble, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
